type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/atim/bottom/repo/fedora-%OS_VERSION%/atim-bottom-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/jplie/budgie-extras/repo/fedora-%OS_VERSION%/jplie-budgie-extras-%OS_VERSION%.repo
install:
  - micro
  - starship
  - rofi
  - fish
  - gh
  - xrandr
  - bottom
  - gnome-tweaks
  - alacritty
  - ImageMagick
  - mpv
  - neovim
  - fontawesome-fonts
  - tumbler
  - budgie-extras
  - screen
  - direnv
  - moby-engine
  - langpacks-en
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
